{
 "title": "Speedtest results - 1Gb/s",
 "description": "Display speedtest.net results (ping, upload and download speed)",
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  {
   "title": "Average download speed / week",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "format": "Mbits",
   "valueName": "avg",
   "targets": [
    {
     "alias": "Download",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" }
     ],
     "measurement": "download",
     "query": "SELECT mean(\"value\") FROM \"download\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Average upload speed / week",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "format": "Mbits",
   "valueName": "avg",
   "targets": [
    {
     "alias": "Upload",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" }
     ],
     "measurement": "upload",
     "query": "SELECT mean(\"value\") FROM \"download\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Average ping latency / week",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "format": "ms",
   "valueName": "avg",
   "targets": [
    {
     "alias": "Ping",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" }
     ],
     "measurement": "ping",
     "query": "SELECT mean(\"value\") FROM \"download\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Upload / Download",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "Mbits" }
   ],
   "targets": [
    {
     "alias": "Download",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"value\") FROM \"download\" WHERE $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Upload",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"value\") FROM \"upload\" WHERE $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Ping Distribution",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ping",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Ping",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "Ping",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"value\") FROM \"ping\" WHERE $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}